version: "3.8"

networks:
  garm-net:
    external: true

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=root
    networks:
      - garm-net
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
          - postgres_data:/var/lib/postgresql/data
          - ./postgres-entrypoint/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
    driver: local
